title = "TypedRemote"
gitRepoUrl = "https://github.com/Downrest/TypedRemote"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
projectName = "TypedRemote"
url = "https://AuthorName.github.io"
baseUrl = "/TypedRemote"
tagline = "Declare remote events and functions, and typecheck with function signatures () -> ()"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2026 Downrest. Built with Moonwave and Docusaurus"
