title = "TypedRemote"
gitRepoUrl = "https://github.com/Downrest/TypedRemote"

gitSourceBranch = "main"
changelog = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
projectName = "TypedRemote"
url = "https://downrest.github.io"
baseUrl = "/TypedRemote"
tagline = "A remote instance wrapper with support for type functions signatures, () -> ()."

[[classOrder]]
classes = ["TypedRemote"]

[[classOrder]]
section = "types"
collapsed = false
classes = ["Event", "Function"]

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2026 Downrest. Built with Moonwave and Docusaurus"
