[package]
name = "downrest/typedremote"
version = "1.0.0"
description = "Declare remote events and functions, and typecheck with function signatures () -> ()"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
