[package]
name = "downrest/typedremote"
version = "1.0.4"
description = "A typed remote wrapper, taking advantage of function types (...) -> (...) for typechecking parameters"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "rokit.toml",
    "README.md"
]

[dependencies]
